# Generated by Django 4.1.3 on 2022-11-27 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_categorydb_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorydb',
            name='Product',
        ),
    ]
