# Generated by Django 4.1.3 on 2022-11-28 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_productdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdb',
            old_name='Category',
            new_name='PCategory',
        ),
    ]
