# Generated by Django 4.1.3 on 2022-12-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_rename_category_productdb_pcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='PPrice',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
